export const EMAIL_CHANGED='EMAIL_CHANGED'
export const PASSWORD_CHANGED="PASSWORD_CHANGED"
export const LOGIN_FAILED='LOGIN_FAILED'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOAD_SPINNER='LOAD_SPINNER'
export const LOGOUT='LOGOUT'
export const FETCH_CURRENTUSER_SUCCESS='FETCH_CURRENTUSER_SUCCESS'
export const FETCH_CURRENTUSER_FAILURE='FETCH_CURRENTUSER_FAILURE'
