export const API_URL = `http://gitgainz.herokuapp.com/api/v1/`
// export const API_URL = 'http://192.168.2.243:3000/api/v1/'

// const API_URL=`http://192.168.2.243:3000/api/v1/`

export const SET_CURRENT_SCHEDULE ='SET_CURRENT_SCHEDULE'
export const FETCH_SCHEDULES_BEGIN='FETCH_SCHEDULES_BEGIN'
export const FETCH_SCHEDULES_SUCCESS='FETCH_SCHEDULES_SUCCESS'
export const FETCH_SCHEDULES_FAILURE='FETCH_SCHEDULES_FAILURE'
export const ADD_NEW_SCHEDULE='ADD_NEW_SCHEDULE'
export const RESET_SCHEDULES='RESET_SCHEDULES'

export const SET_WORKOUTS='SET_WORKOUTS'
export const SET_CURRENT_WORKOUT ='SET_CURRENT_WORKOUT'
export const FETCH_WORKOUTS_BEGIN='FETCH_WORKOUTS_BEGIN'
export const FETCH_WORKOUTS_SUCCESS='FETCH_WORKOUTS_SUCCESS'
export const FETCH_WORKOUTS_FAILURE='FETCH_WORKOUTS_FAILURE'
export const ADD_NEW_WORKOUT ='ADD_WORKOUT'
export const RESET_WORKOUTS='RESET_WORKOUTS'
export const START_WORKOUT='START_WORKOUT'
export const STOP_WORKOUT='STOP_WORKOUT'
export const STARTSTOP_WORKOUT='STARTSTOP_WORKOUT'

export const FETCH_EXERCISES_BEGIN='FETCH_EXERCISES_BEGIN'
export const FETCH_EXERCISES_SUCCESS='FETCH_EXERCISES_SUCCESS'
export const FETCH_EXERCISES_FAILURE='FETCH_EXERCISES_FAILURE'
export const ADD_NEW_EXERCISE='ADD_NEW_EXERCISE'
export const RESET_EXERCISES='RESET_EXERCISES'

export const FETCH_SCHEDULES_WORKOUTS= 'FETCH_SCHEDULES_WORKOUTS'

export const FETCH_CIRCUITS_BEGIN='FETCH_CIRCUITS_BEGIN'
export const FETCH_CIRCUITS_SUCCESS='FETCH_CIRCUITS_SUCCESS'
export const FETCH_CIRCUITS_FAILURE='FETCH_CIRCUITS_FAILURE'
export const ADD_CIRCUIT='ADD_CIRCUIT'
export const DELETE_CIRCUIT='DELETE_CIRCUIT'
export const RESET_CIRCUITS='RESET_CIRCUITS'

export const FETCH_USER_WORKOUTS_BEGIN='FETCH_USER_WORKOUTS_BEGIN'
export const FETCH_USER_WORKOUTS_SUCCESS='FETCH_USER_WORKOUTS_SUCCESS'
export const FETCH_USER_WORKOUTS_FAILURE='FETCH_USER_WORKOUTS_FAILURE'


export const FETCH_MUSCLES_BEGIN='FETCH_MUSCLES_BEGIN'
export const FETCH_MUSCLES_SUCCESS='FETCH_MUSCLES_SUCCESS'
export const FETCH_MUSCLES_FAILURE='FETCH_MUSCLES_FAILURE'
export const FETCH_MUSCLEREPS='FETCH_MUSCLEREPS'
export const FETCH_MUSCLESETS='FETCH_MUSCLESETS'
export const SET_MUSCLES='SET_MUSCLES'
export const RESET_MUSCLES='RESET_MUSCLES'

//completedworkout constants
export const SET_COMPLETEDWORKOUTS="SET_COMPLETEDWORKOUTS"
export const FETCH_COMPLETEDWORKOUTS_BEGIN="FETCH_COMPLETEDWORKOUTS_BEGIN"
export const FETCH_COMPLETEDWORKOUTS_FAILURE="FETCH_COMPLETEDWORKOUTS_FAILURE"
export const FETCH_COMPLETEDWORKOUTS_SUCCESS="FETCH_COMPLETEDWORKOUTS_SUCCESS"

export const ADD_COMPLETEDWORKOUT="ADD_COMPLETEDWORKOUT"
